### ISSUE TITLE
Create custom components

### ISSUE THREAD

**Issue by felixerdy** [reedu-reengineering-education/likert-o-mat-2.0#13]
- Follow up of #8

Custom

- Montag, den 28.08.23

- [x] survey 
- [x] (Titel etc... )  

-  Dienstag, den 29.08.23

- [x] Slider (Question & Answer mode)

- [x] Title

- [x]  (Description)

- [x] Steps: number
  - min: (number | string)
  - max: (number | string)

- [x] Layout

- [x] Navbar: e.g. https://github.com/shadcn-ui/next-template/blob/main/components/site-header.tsx

**Comment by georgi-s** [comment]
done
